// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmV90JkfoCpReoSnY5q2sKshxaSdk7TY8',
    appId: '1:1062087788607:web:068966a3a45e512105d08a',
    messagingSenderId: '1062087788607',
    projectId: 'spotifyappfp01-1e591',
    authDomain: 'spotifyappfp01-1e591.firebaseapp.com',
    storageBucket: 'spotifyappfp01-1e591.firebasestorage.app',
    measurementId: 'G-FN0Y2R1YP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAehIEDclWsKtD2ImGeNfABM3A-B1JTJRc',
    appId: '1:1062087788607:android:9ca2bcc64795ae1205d08a',
    messagingSenderId: '1062087788607',
    projectId: 'spotifyappfp01-1e591',
    storageBucket: 'spotifyappfp01-1e591.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_Swq2oQHHSIM6upyZeSYGONfMUv0Qu1I',
    appId: '1:1062087788607:ios:880bff115f9d5ab005d08a',
    messagingSenderId: '1062087788607',
    projectId: 'spotifyappfp01-1e591',
    storageBucket: 'spotifyappfp01-1e591.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_Swq2oQHHSIM6upyZeSYGONfMUv0Qu1I',
    appId: '1:1062087788607:ios:880bff115f9d5ab005d08a',
    messagingSenderId: '1062087788607',
    projectId: 'spotifyappfp01-1e591',
    storageBucket: 'spotifyappfp01-1e591.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmV90JkfoCpReoSnY5q2sKshxaSdk7TY8',
    appId: '1:1062087788607:web:aa98dd196a52068e05d08a',
    messagingSenderId: '1062087788607',
    projectId: 'spotifyappfp01-1e591',
    authDomain: 'spotifyappfp01-1e591.firebaseapp.com',
    storageBucket: 'spotifyappfp01-1e591.firebasestorage.app',
    measurementId: 'G-VZFBJ02MEV',
  );
}
